baseURL: "https://thenoesis12.netlify.app"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
